version: '3'

services:
  mysql:
    container_name: ${APP_NAME}_mysql
    image: mysql
    volumes:
      - ./docker-assets/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql_data:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: '${DB_PASSWORD}'
